###

GET http://localhost:9999/customers/1 HTTP/1.1
//GET http://localhost:9999/customers.getById?id=1&title=Депозиты с доходом 60/40 HTTP/1.1 HTTP/1.1

###

POST http://localhost:9999/customers/7/block HTTP/1.1


###

DELETE http://localhost:9999/customers/1/unblock HTTP/1.1


###

GET http://localhost:9999/customers.removeById?id=6 HTTP/1.1


###

GET http://localhost:9999/customers HTTP/1.1

###

GET http://localhost:9999/customers/active HTTP/1.1

###

GET http://localhost:9999/customers.save?id=0&title=Депозиты с доходом 60/40&content=Вкладывайте депозит в национальной валюте&button=Рассчитать доход&link=https://alif.tj/deposit#CountYourIncome HTTP/1.1

###

GET http://localhost:9999/customers.removeById?id=5 HTTP/1.1


###

POST http://localhost:9999/customers HTTP/1.1
Content-Type: application/json

{
    "id": 0,
    "name": "Katya",
    "phone": "+992000000002"
}